version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf dist

  build:
    desc: Build
    cmds:
      - goreleaser build --clean --snapshot

  build-single:
    desc: Build (single)
    cmds:
      - goreleaser build --clean --snapshot --single-target --output dist/hydra-login-consent-test

  dependencyUpdates:
    desc: Show dependency updates
    cmds:
      - go mod download
      - go mod tidy
      - go list -u -m -json all | go-mod-outdated -update -direct

  mingo:
    cmds:
      - mise exec go@1.25.0 -- mise install 'go:github.com/bobg/mingo/cmd/mingo@0.14.0'
      - mise exec 'go:github.com/bobg/mingo/cmd/mingo@0.14.0' -- mingo -tests -v

  run:
    desc: Run
    deps: [ build-single ]
    cmds:
      - dist/hydra-login-consent-test serve --config-file config.toml
